"""Generate rich catalog data meeting 30K+ word requirement."""
import json, os

DATA_DIR = os.path.join(os.path.dirname(__file__), "Data")

COURSES = [
  {"course":"CS101","title":"Introduction to Programming","credits":4,"prerequisites":"None","corequisites":"None","terms":["Fall","Spring","Summer"],
   "description":"This foundational course introduces students to the principles and practice of computer programming using Python. Students learn to design, write, test, and debug programs that solve real-world problems. The course covers fundamental programming concepts including variables, data types, control structures (conditionals and loops), functions, file I/O, and basic object-oriented programming. Students develop computational thinking skills and learn to decompose complex problems into manageable components. Weekly lab sessions provide hands-on practice with programming exercises of increasing complexity. The course emphasizes good coding practices including documentation, testing, and version control. No prior programming experience is required. Students who have significant programming experience should consider placing into CS102 via the department placement exam.",
   "topics":["Variables and data types","Control structures: if/else, while, for","Functions and parameter passing","Lists, dictionaries, and tuples","File input/output","Introduction to classes and objects","Debugging techniques","Algorithm design basics","String manipulation","Error handling with exceptions","Basic recursion","Simple sorting algorithms"],
   "outcomes":["Write Python programs to solve computational problems","Apply control structures and functions to decompose problems","Use basic data structures to organize information","Debug programs systematically using print statements and debuggers","Follow coding conventions and write readable, documented code","Explain the difference between compile-time and run-time errors"]},

  {"course":"CS102","title":"Object-Oriented Programming","credits":4,"prerequisites":"Completion of CS101 with a minimum grade of C","corequisites":"None","terms":["Fall","Spring"],
   "description":"Building on the foundation established in CS101, this course provides comprehensive coverage of object-oriented programming (OOP) principles using Java. Students learn to design and implement programs using classes, objects, inheritance, polymorphism, encapsulation, and abstraction. The course covers advanced data structures including linked lists, stacks, and queues, as well as introduction to generic programming and exception handling. Significant emphasis is placed on software design principles, UML diagrams, and unit testing with JUnit. Students complete a substantial individual project and several collaborative programming assignments. The course also introduces students to integrated development environments (IDEs) and professional software development workflows. Students must have earned at least a C in CS101 to enroll; students with a D or below must retake CS101 first.",
   "topics":["Classes, objects, and constructors","Inheritance and method overriding","Polymorphism and dynamic binding","Abstract classes and interfaces","Encapsulation and access modifiers","Exception handling and custom exceptions","Generic types and collections framework","Linked lists, stacks, and queues","UML class diagrams","Unit testing with JUnit","File I/O and serialization","Introduction to GUI programming"],
   "outcomes":["Design object-oriented solutions using UML class diagrams","Implement inheritance hierarchies with polymorphism","Write robust code with proper exception handling","Create and use generic classes and methods","Implement fundamental linked data structures","Write comprehensive unit tests for Java programs"]},

  {"course":"CS201","title":"Data Structures and Algorithms","credits":4,"prerequisites":"CS102 AND MATH120","corequisites":"None","terms":["Fall","Spring"],
   "description":"This core course provides in-depth study of fundamental data structures and the algorithms that operate on them. Students learn to analyze algorithm efficiency using Big-O notation and select appropriate data structures for specific applications. Topics include arrays, linked lists, trees (binary, AVL, B-trees), heaps, hash tables, and graphs. Algorithm topics include sorting (mergesort, quicksort, heapsort), searching, graph traversal (BFS, DFS), shortest path algorithms, and introduction to dynamic programming. Students implement major data structures from scratch in Java/C++ and analyze their time and space complexity. Prerequisites include CS102 (for OOP proficiency) and MATH120 (for mathematical maturity needed for algorithm analysis). Weekly problem sets combine implementation with theoretical analysis.",
   "topics":["Algorithm analysis and Big-O notation","Arrays and dynamic arrays","Linked lists (singly, doubly, circular)","Stacks and queues (array and linked implementations)","Binary trees and binary search trees","Balanced trees: AVL trees and Red-Black trees","Priority queues and heaps","Hash tables and collision resolution","Graph representations and traversals","Sorting algorithms: mergesort, quicksort, heapsort","Shortest path: Dijkstra and Bellman-Ford","Introduction to dynamic programming"],
   "outcomes":["Analyze algorithm time and space complexity using Big-O notation","Implement and use fundamental data structures","Select appropriate data structures for given problems","Implement and compare sorting and searching algorithms","Apply graph algorithms to solve connectivity and path problems","Prove correctness of simple algorithms using loop invariants"]},

  {"course":"CS202","title":"Discrete Mathematics for Computer Science","credits":3,"prerequisites":"MATH120","corequisites":"None","terms":["Fall","Spring"],
   "description":"This course covers the mathematical foundations essential for computer science. Topics include propositional and predicate logic, proof techniques (direct proof, contradiction, induction), set theory, relations, functions, combinatorics, probability, graph theory, and formal languages. The course emphasizes mathematical reasoning and proof writing as skills fundamental to algorithm design, database theory, cryptography, and theoretical computer science. Students learn to construct rigorous proofs and apply discrete mathematical structures to computational problems. Regular homework assignments include both written proofs and computational exercises. Prior completion of MATH120 (Calculus I) is required for the mathematical maturity needed for proof-based coursework. Students are expected to have comfort with algebraic manipulation and basic mathematical notation.",
   "topics":["Propositional logic and truth tables","Predicate logic and quantifiers","Proof techniques: direct, contrapositive, contradiction","Mathematical induction and strong induction","Set theory and set operations","Relations: equivalence relations, partial orders","Functions: injective, surjective, bijective","Counting: permutations, combinations, pigeonhole principle","Discrete probability","Graph theory: paths, cycles, trees, planarity","Recurrence relations","Introduction to formal languages and automata"],
   "outcomes":["Construct rigorous mathematical proofs using various techniques","Apply mathematical induction to prove statements about natural numbers","Analyze problems using combinatorial counting methods","Model computational problems using graphs and relations","Calculate probabilities for discrete random events","Solve recurrence relations arising from algorithm analysis"]},

  {"course":"MATH120","title":"Calculus I","credits":4,"prerequisites":"None. Students should have completed pre-calculus or equivalent.","corequisites":"None","terms":["Fall","Spring","Summer"],
   "description":"The first course in the calculus sequence covering limits, continuity, differentiation, and introduction to integration. Students study the concept of a limit, techniques of differentiation including the power rule, product rule, quotient rule, and chain rule, and applications of derivatives including optimization, related rates, and curve sketching. The course introduces the definite integral through Riemann sums and covers the Fundamental Theorem of Calculus. Applications include area under curves, average value, and introductory differential equations. This course is required for CS students as it provides the mathematical foundation for algorithm analysis, machine learning, and scientific computing. Students should have a strong background in algebra and trigonometry. A graphing calculator is required.",
   "topics":["Limits and continuity","Definition of the derivative","Differentiation rules and techniques","Applications of derivatives","Mean Value Theorem","Curve sketching","Optimization problems","Related rates","Antiderivatives","Definite integrals and Riemann sums","Fundamental Theorem of Calculus","Applications of integration"],
   "outcomes":["Evaluate limits using algebraic and graphical methods","Compute derivatives using differentiation rules","Apply derivatives to optimization and related rates problems","Evaluate definite and indefinite integrals","Apply the Fundamental Theorem of Calculus","Model real-world problems using calculus concepts"]},

  {"course":"MATH220","title":"Linear Algebra","credits":3,"prerequisites":"MATH120","corequisites":"None","terms":["Fall","Spring"],
   "description":"This course covers the fundamentals of linear algebra with applications to computer science and data science. Topics include systems of linear equations, matrix algebra, determinants, vector spaces, linear transformations, eigenvalues and eigenvectors, orthogonality, and least squares. The course emphasizes both computational techniques and theoretical understanding. Applications to computer graphics, machine learning, data compression, and network analysis are highlighted throughout. Linear algebra is essential for students pursuing machine learning (CS305), deep learning (CS322), computer graphics (CS312), and related areas. Prerequisite: MATH120 for foundational mathematical maturity.",
   "topics":["Systems of linear equations and Gaussian elimination","Matrix operations and matrix algebra","Determinants and their properties","Vector spaces and subspaces","Linear independence and basis","Linear transformations","Eigenvalues and eigenvectors","Orthogonality and Gram-Schmidt process","Least squares approximation","Singular Value Decomposition introduction","Applications to computer graphics","Applications to machine learning"],
   "outcomes":["Solve systems of linear equations using matrix methods","Perform matrix operations and compute determinants","Understand and apply vector space concepts","Compute eigenvalues and eigenvectors","Apply orthogonality concepts to least squares problems","Connect linear algebra to applications in CS and data science"]},

  {"course":"MATH230","title":"Probability and Statistics","credits":3,"prerequisites":"MATH120","corequisites":"None","terms":["Fall","Spring"],
   "description":"Introduction to probability theory and statistical methods with applications in computer science. Covers sample spaces, conditional probability, Bayes theorem, random variables, common distributions (binomial, Poisson, normal, exponential), expectation and variance, hypothesis testing, confidence intervals, and linear regression. Applications include algorithm analysis, machine learning foundations, network reliability, and data analysis. This course provides the statistical foundation needed for machine learning and data science coursework. Students learn to use statistical software (R or Python) for data analysis projects.",
   "topics":["Sample spaces and events","Conditional probability and Bayes theorem","Discrete and continuous random variables","Common probability distributions","Expectation, variance, and covariance","Central Limit Theorem","Hypothesis testing","Confidence intervals","Simple and multiple linear regression","Bayesian inference basics","Monte Carlo simulation","Statistical computing with Python/R"],
   "outcomes":["Apply probability rules to compute event probabilities","Model real-world phenomena using probability distributions","Perform hypothesis tests and construct confidence intervals","Apply Bayes theorem to update beliefs with evidence","Conduct linear regression analysis","Use statistical software for data analysis"]},

  {"course":"CS301","title":"Design and Analysis of Algorithms","credits":3,"prerequisites":"CS201 AND CS202","corequisites":"None","terms":["Fall","Spring"],
   "description":"Advanced study of algorithm design paradigms and complexity analysis. This course extends the algorithmic foundations from CS201 to cover divide-and-conquer, greedy algorithms, dynamic programming, network flow, and introduction to NP-completeness. Students learn to prove algorithm correctness, analyze worst-case and average-case complexity, and select appropriate algorithmic strategies for different problem types. The course includes significant theoretical content including amortized analysis, randomized algorithms, and computational complexity classes. Both CS201 (for data structures proficiency) and CS202 (for proof techniques and mathematical maturity) are required prerequisites. Students will complete algorithm design projects and written proof assignments throughout the semester.",
   "topics":["Divide and conquer: master theorem, Strassen's algorithm","Greedy algorithms: activity selection, Huffman coding","Dynamic programming: knapsack, sequence alignment, shortest paths","Graph algorithms: MST (Prim, Kruskal), network flow","Amortized analysis","Randomized algorithms","NP-completeness and reductions","Approximation algorithms","String matching algorithms","Computational geometry basics","Lower bounds and decision trees","Advanced sorting and selection"],
   "outcomes":["Design algorithms using divide-and-conquer, greedy, and DP paradigms","Prove algorithm correctness using loop invariants and induction","Analyze algorithm complexity using recurrences and amortized analysis","Identify NP-complete problems and apply reductions","Apply network flow algorithms to optimization problems","Select appropriate algorithmic paradigms for given problem types"]},

  {"course":"CS302","title":"Database Management Systems","credits":3,"prerequisites":"CS201 OR approval from the instructor","corequisites":"None","terms":["Fall","Spring"],
   "description":"Comprehensive study of database systems covering relational data model, SQL, database design, normalization, transaction processing, and query optimization. Students learn to design efficient database schemas using ER modeling and normalization theory (up to BCNF), write complex SQL queries including joins, subqueries, and aggregation, and understand the internals of database engines including indexing (B+ trees, hash indexes), query processing, and concurrency control. The course includes a substantial group project involving full database application development. Students need either CS201 (recommended for understanding of data structures used in database internals) or instructor approval for students with equivalent background from other programs.",
   "topics":["Entity-Relationship modeling","Relational model and relational algebra","SQL: DDL, DML, complex queries","Normalization: 1NF through BCNF","Indexing: B+ trees and hash indexes","Query processing and optimization","Transaction processing and ACID properties","Concurrency control and locking","Recovery and logging","NoSQL databases overview","Database application development","Stored procedures and triggers"],
   "outcomes":["Design normalized database schemas from requirements","Write complex SQL queries for data retrieval and manipulation","Explain and apply normalization theory through BCNF","Understand indexing structures and query optimization","Implement transaction processing with proper isolation","Develop a complete database-backed application"]},

  {"course":"CS303","title":"Operating Systems","credits":4,"prerequisites":"Students must have completed both CS201 and CS202 before enrolling","corequisites":"CS303L (Operating Systems Lab)","terms":["Fall"],
   "description":"Study of operating system principles including process management, memory management, file systems, and I/O management. Students learn about process scheduling algorithms, inter-process communication (IPC), synchronization primitives (mutexes, semaphores, monitors), deadlock detection and prevention, virtual memory with paging and segmentation, and file system implementations. The course includes substantial systems programming assignments in C, requiring students to implement simplified versions of OS components. Students must have completed both CS201 (for data structures used in OS internals) and CS202 (for mathematical foundations of scheduling analysis). A concurrent co-requisite lab section CS303L provides hands-on experience with Linux kernel programming. Note: This course is typically offered only in the Fall semester.",
   "topics":["Process management and scheduling algorithms","Threads and concurrent programming","Synchronization: mutexes, semaphores, condition variables","Deadlock: detection, prevention, avoidance","Memory management: paging, segmentation","Virtual memory and page replacement algorithms","File systems: FAT, ext4, journaling","I/O management and device drivers","Inter-process communication","Protection and security basics","Virtualization concepts","Case study: Linux kernel"],
   "outcomes":["Explain and compare process scheduling algorithms","Implement concurrent programs with proper synchronization","Analyze and prevent deadlock situations","Explain virtual memory mechanisms and page replacement policies","Understand file system organization and implementation","Write systems-level programs in C using POSIX APIs"]},

  {"course":"CS304","title":"Computer Networks","credits":3,"prerequisites":"CS201","corequisites":"None","terms":["Fall","Spring"],
   "description":"Introduction to computer networking covering the TCP/IP protocol stack, network architectures, and distributed applications. The course follows a top-down approach starting with application-layer protocols (HTTP, DNS, SMTP) and progressing through transport (TCP, UDP), network (IP, routing), and link layers. Students study socket programming, reliable data transfer, congestion control, routing algorithms, and network security fundamentals. Lab assignments involve implementing network protocols and applications using Python socket programming. The prerequisite CS201 provides the data structures knowledge needed for implementing networking algorithms and protocol state machines.",
   "topics":["Network architecture and TCP/IP model","Application layer: HTTP, DNS, SMTP, FTP","Socket programming in Python","Transport layer: TCP, UDP","Reliable data transfer protocols","Congestion control","Network layer: IP addressing and subnetting","Routing algorithms: link-state, distance-vector","Data link layer and MAC protocols","Wireless networking","Network security: TLS, firewalls","Software-defined networking introduction"],
   "outcomes":["Explain the TCP/IP protocol stack and encapsulation","Implement client-server applications using sockets","Analyze TCP congestion control behavior","Design IP addressing schemes with subnetting","Compare routing algorithms and their convergence properties","Understand network security threats and countermeasures"]},

  {"course":"CS305","title":"Machine Learning","credits":3,"prerequisites":"CS301 AND MATH220","corequisites":"MATH230 (may be taken concurrently)","terms":["Fall","Spring"],
   "description":"Introduction to machine learning theory and practice covering supervised learning, unsupervised learning, and foundations of deep learning. Students study linear regression, logistic regression, support vector machines, decision trees, random forests, neural networks, k-means clustering, PCA, and model evaluation techniques. The course emphasizes both mathematical foundations and practical implementation using Python (scikit-learn, NumPy, pandas). Prerequisites include CS301 (for algorithmic analysis skills) and MATH220 (linear algebra is essential for understanding ML algorithms). MATH230 (Probability and Statistics) is a co-requisite that may be taken concurrently — the statistical foundations are needed for the second half of the course covering model evaluation, Bayesian methods, and generalization theory.",
   "topics":["Supervised vs unsupervised learning","Linear regression and gradient descent","Logistic regression and classification","Support vector machines","Decision trees and random forests","Neural networks and backpropagation","K-means clustering and hierarchical clustering","Principal Component Analysis (PCA)","Model evaluation: cross-validation, ROC curves","Bias-variance tradeoff","Ensemble methods: bagging, boosting","Feature engineering and selection"],
   "outcomes":["Implement supervised and unsupervised learning algorithms","Apply appropriate ML models to different problem types","Evaluate model performance using proper validation techniques","Understand the mathematical foundations of core ML algorithms","Use scikit-learn and pandas for practical ML projects","Analyze bias-variance tradeoff and combat overfitting"]},

  {"course":"CS306","title":"Artificial Intelligence","credits":3,"prerequisites":"CS301","corequisites":"None","terms":["Spring"],
   "description":"Survey of artificial intelligence techniques including search algorithms, knowledge representation, planning, reasoning under uncertainty, and introduction to natural language processing and computer vision. Students study uninformed and informed search (A*, heuristic design), constraint satisfaction problems, game-playing (minimax, alpha-beta pruning), propositional and first-order logic, Bayesian networks, Markov decision processes, and reinforcement learning foundations. The course includes programming projects implementing AI agents for games, planning domains, and probabilistic reasoning. CS301 is required for algorithm design skills essential for implementing search and optimization algorithms. Note: this course is typically offered in Spring semester only.",
   "topics":["Intelligent agents and environments","Uninformed search: BFS, DFS, iterative deepening","Informed search: A*, heuristics, IDA*","Constraint satisfaction problems","Adversarial search: minimax, alpha-beta pruning","Propositional and first-order logic","Knowledge representation and inference","Bayesian networks and probabilistic inference","Markov Decision Processes","Reinforcement learning basics","Natural language processing overview","Computer vision overview"],
   "outcomes":["Design and implement search algorithms for problem solving","Formulate problems as constraint satisfaction problems","Build game-playing agents using adversarial search","Apply probabilistic reasoning using Bayesian networks","Understand Markov Decision Processes and reinforcement learning","Evaluate AI systems in terms of rationality and performance"]},

  {"course":"CS307","title":"Software Engineering","credits":3,"prerequisites":"CS201","corequisites":"None","terms":["Fall","Spring"],
   "description":"Study of software engineering principles, methodologies, and practices for developing large-scale software systems. Covers requirements engineering, software architecture and design patterns, agile development (Scrum, Kanban), version control with Git, continuous integration/continuous deployment (CI/CD), testing strategies (unit, integration, system, acceptance), code quality metrics, and project management. Students work in teams on a semester-long software project following agile methodology with regular sprint reviews. The course emphasizes practical skills including code review, refactoring, and technical documentation. Prerequisite: CS201 ensures students have sufficient programming maturity for team-based development.",
   "topics":["Software development lifecycle models","Requirements engineering and user stories","Software architecture patterns","Design patterns: observer, factory, strategy, MVC","Version control with Git and GitHub","Agile development: Scrum and Kanban","Testing: unit, integration, system, acceptance","CI/CD pipelines","Code quality and refactoring","Project management and estimation","Technical documentation","Ethics in software engineering"],
   "outcomes":["Apply agile development methodology to team projects","Design software architectures using appropriate patterns","Write requirements specifications and user stories","Implement comprehensive testing strategies","Use version control and CI/CD tools professionally","Manage software projects with proper estimation and tracking"]},

  {"course":"CS308","title":"Cybersecurity Fundamentals","credits":3,"prerequisites":"CS201 OR CS304","corequisites":"None","terms":["Fall","Spring"],
   "description":"Introduction to cybersecurity covering threat modeling, cryptography, network security, web security, and security policy. Students study symmetric and asymmetric encryption, hash functions, digital signatures, PKI, common attack vectors (SQL injection, XSS, buffer overflow), intrusion detection, access control models, and security risk assessment. Lab exercises involve hands-on penetration testing in controlled environments, cryptographic implementations, and security auditing. Students need either CS201 (data structures for understanding security algorithm implementations) or CS304 (networking knowledge for network security topics) as a prerequisite.",
   "topics":["Security principles: CIA triad","Threat modeling and risk assessment","Symmetric cryptography: AES, DES","Asymmetric cryptography: RSA, Diffie-Hellman","Hash functions and digital signatures","Public Key Infrastructure (PKI)","Network security: firewalls, IDS/IPS","Web security: SQL injection, XSS, CSRF","Authentication and access control","Malware analysis basics","Security auditing and penetration testing","Security policies and compliance"],
   "outcomes":["Apply threat modeling to identify system vulnerabilities","Implement and analyze cryptographic algorithms","Identify and mitigate common web application vulnerabilities","Configure network security tools and firewalls","Perform basic security audits and penetration tests","Develop security policies for organizational compliance"]},

  {"course":"CS309","title":"Cloud Computing","credits":3,"prerequisites":"CS201","corequisites":"None","terms":["Spring"],
   "description":"Introduction to cloud computing architectures, services, and deployment models. Covers IaaS, PaaS, SaaS, virtualization, containerization (Docker, Kubernetes), serverless computing, cloud storage systems, and distributed computing patterns. Students gain hands-on experience with major cloud platforms (AWS/Azure/GCP) through lab exercises deploying and managing cloud applications. Topics include auto-scaling, load balancing, microservices architecture, and cloud security. The prerequisite CS201 provides data structures knowledge needed for understanding distributed data storage and processing systems. This course is typically offered in Spring semester.",
   "topics":["Cloud service models: IaaS, PaaS, SaaS","Virtualization and hypervisors","Containers and Docker","Container orchestration with Kubernetes","Serverless computing (AWS Lambda)","Cloud storage: S3, Block, Object","Auto-scaling and load balancing","Microservices architecture","Cloud security and IAM","DevOps practices","Cost optimization","Multi-cloud strategies"],
   "outcomes":["Design and deploy applications on cloud platforms","Containerize applications using Docker","Orchestrate containers with Kubernetes","Implement auto-scaling and load balancing","Apply cloud security best practices","Evaluate cost and performance of cloud architectures"]},

  {"course":"CS310","title":"Distributed Systems","credits":3,"prerequisites":"CS303 AND CS304","corequisites":"None","terms":["Spring"],
   "description":"Advanced study of distributed systems covering consistency models, distributed consensus, fault tolerance, and distributed data storage. Topics include clock synchronization, logical clocks, distributed mutual exclusion, consensus protocols (Paxos, Raft), distributed hash tables, MapReduce, and microservices communication patterns. Prerequisites include CS303 (OS concepts for process management and concurrency) and CS304 (networking for distributed communication). Students implement distributed system components and analyze their correctness and performance properties.",
   "topics":["Distributed system models and challenges","Clock synchronization and logical clocks","Distributed mutual exclusion","Consensus: Paxos, Raft","Distributed hash tables","Replication and consistency models","Fault tolerance and Byzantine failures","MapReduce and distributed computing","CAP theorem","Distributed transactions","Microservices and RPC","Blockchain as distributed system"],
   "outcomes":["Analyze distributed system correctness using formal models","Implement consensus protocols for distributed agreement","Design fault-tolerant distributed applications","Apply consistency models to distributed storage systems","Implement MapReduce programs for large-scale data processing","Evaluate tradeoffs in distributed system design (CAP theorem)"]},

  {"course":"CS311","title":"Human-Computer Interaction","credits":3,"prerequisites":"CS102","corequisites":"None","terms":["Fall","Spring"],
   "description":"Study of human-computer interaction principles, user interface design, usability evaluation, and user experience research. Covers design thinking, user-centered design process, prototyping (paper and digital), heuristic evaluation, usability testing, accessibility (WCAG guidelines), and interaction design patterns. Students complete a semester-long UX project including user research, iterative prototyping, and usability testing with real users. Prerequisite: CS102 provides programming skills needed for implementing interactive prototypes.",
   "topics":["Human factors and cognitive psychology","User-centered design process","Design thinking methodology","Paper and digital prototyping","Heuristic evaluation (Nielsen's heuristics)","Usability testing methods","Accessibility and WCAG guidelines","Interaction design patterns","Mobile and responsive design","Information architecture","Visual design principles","Emerging interfaces: VR/AR, voice"],
   "outcomes":["Apply user-centered design methodology","Conduct user research using interviews and surveys","Create paper and digital prototypes","Perform heuristic evaluation of user interfaces","Conduct usability tests and analyze results","Design accessible interfaces following WCAG guidelines"]},

  {"course":"CS312","title":"Computer Graphics","credits":3,"prerequisites":"CS201 AND MATH220","corequisites":"None","terms":["Spring"],
   "description":"Introduction to computer graphics covering 2D and 3D rendering, geometric transformations, lighting models, and GPU programming. Students study the graphics pipeline, coordinate transformations, rasterization, texture mapping, ray tracing, and shader programming using OpenGL/WebGL. MATH220 (Linear Algebra) is essential for understanding geometric transformations, projections, and lighting computations. CS201 provides the data structures knowledge (trees, spatial data structures) needed for scene management and rendering optimization.",
   "topics":["Graphics pipeline overview","2D and 3D geometric transformations","Viewing and projection","Rasterization and clipping","Lighting models: Phong, Blinn-Phong","Texture mapping","Shadow algorithms","Ray tracing","Shader programming (GLSL)","Scene graphs and spatial data structures","Animation basics","GPU architecture overview"],
   "outcomes":["Implement the graphics rendering pipeline","Apply geometric transformations using matrices","Write vertex and fragment shaders","Implement lighting models and texture mapping","Build a basic ray tracer","Understand GPU architecture and parallel rendering"]},

  {"course":"CS313","title":"Natural Language Processing","credits":3,"prerequisites":"CS305","corequisites":"None","terms":["Spring"],
   "description":"Study of computational methods for processing and understanding human language. Covers text preprocessing, language models, word embeddings, sequence models (RNNs, LSTMs), attention mechanisms, transformers, and applications including sentiment analysis, machine translation, question answering, and text generation. Students implement NLP pipelines using Python (NLTK, spaCy, HuggingFace Transformers). CS305 (Machine Learning) is the prerequisite as NLP builds heavily on ML foundations including neural networks, optimization, and model evaluation.",
   "topics":["Text preprocessing and tokenization","Language models: n-gram and neural","Word embeddings: Word2Vec, GloVe","Recurrent Neural Networks and LSTMs","Attention mechanisms","Transformer architecture","BERT and GPT models","Sentiment analysis","Named entity recognition","Machine translation","Question answering systems","Text generation and summarization"],
   "outcomes":["Implement text preprocessing pipelines","Train and evaluate language models","Apply word embeddings to NLP tasks","Implement sequence models for text classification","Fine-tune pre-trained transformer models","Build end-to-end NLP applications"]},

  {"course":"CS314","title":"Big Data Analytics","credits":3,"prerequisites":"CS305","corequisites":"None","terms":["Fall"],
   "description":"Introduction to big data processing frameworks and analytics techniques for large-scale datasets. Covers Hadoop ecosystem (HDFS, MapReduce, Hive), Apache Spark, stream processing (Kafka, Flink), data warehousing, and large-scale machine learning. Students work with real-world datasets and cloud-based big data platforms. CS305 is the prerequisite for machine learning foundations needed for large-scale analytics and distributed ML algorithms.",
   "topics":["Big data characteristics and challenges","Hadoop ecosystem: HDFS, MapReduce","Apache Spark: RDDs, DataFrames, SparkSQL","Stream processing with Kafka and Flink","Data warehousing and data lakes","NoSQL databases for big data","Large-scale machine learning with MLlib","Data pipeline design","Data quality and governance","Visualization for big data","Cloud-based big data services","Real-time analytics"],
   "outcomes":["Process large datasets using Hadoop and Spark","Design data pipelines for batch and stream processing","Apply machine learning at scale using distributed frameworks","Query large datasets using SparkSQL and Hive","Design data warehouse schemas","Evaluate big data architecture tradeoffs"]},

  {"course":"CS315","title":"Information Retrieval","credits":3,"prerequisites":"CS301","corequisites":"None","terms":["Fall"],
   "description":"Study of information retrieval systems covering indexing, retrieval models, evaluation, and modern search engine architecture. Topics include inverted indexes, TF-IDF, BM25, vector space model, query processing, relevance feedback, web crawling, link analysis (PageRank), and introduction to learning-to-rank. CS301 is required for algorithm design and analysis skills essential for implementing efficient retrieval systems and understanding complexity of ranking algorithms.",
   "topics":["Inverted index construction","Boolean retrieval model","TF-IDF weighting","Vector space model","BM25 and probabilistic retrieval","Query processing and optimization","Relevance feedback and query expansion","Web crawling and indexing","Link analysis: PageRank, HITS","Evaluation metrics: precision, recall, MAP, NDCG","Learning to rank","Semantic search and embeddings"],
   "outcomes":["Build inverted indexes for text collections","Implement TF-IDF and BM25 retrieval models","Evaluate retrieval systems using standard metrics","Implement web crawling and link analysis algorithms","Apply learning-to-rank techniques","Design and evaluate search engine components"]},

  {"course":"CS316","title":"Compiler Design","credits":3,"prerequisites":"CS301 AND CS202","corequisites":"None","terms":["Fall"],
   "description":"Study of compiler construction covering lexical analysis, parsing, semantic analysis, intermediate code generation, optimization, and code generation. Students implement a compiler for a simple programming language through a series of progressive assignments. Topics include regular expressions and finite automata, context-free grammars, LL and LR parsing, type checking, intermediate representations, and basic optimization techniques. Both CS301 (for algorithm design) and CS202 (for formal languages and automata theory foundations) are required.",
   "topics":["Lexical analysis and regular expressions","Finite automata: DFA and NFA","Context-free grammars","Parsing: top-down (LL) and bottom-up (LR)","Abstract syntax trees","Semantic analysis and type checking","Symbol tables","Intermediate code generation","Code optimization techniques","Register allocation","Code generation","Runtime environments"],
   "outcomes":["Implement a lexical analyzer using regular expressions","Build parsers using LL and LR techniques","Construct abstract syntax trees from source code","Perform type checking and semantic analysis","Generate intermediate code representations","Apply basic code optimization techniques"]},

  {"course":"CS317","title":"Embedded Systems","credits":3,"prerequisites":"CS201","corequisites":"None","terms":["Spring"],
   "description":"Introduction to embedded systems design covering microcontroller programming, real-time systems, hardware-software interfaces, and IoT applications. Students program ARM-based microcontrollers using C and assembly, interface with sensors and actuators, and learn about real-time operating systems (RTOS). Lab work involves hands-on projects with development boards. CS201 is required for data structures knowledge and C programming proficiency needed for systems-level embedded programming.",
   "topics":["Microcontroller architecture (ARM)","Embedded C programming","Digital I/O and GPIO","Interrupts and interrupt handling","Timers and PWM","Serial communication: UART, SPI, I2C","Analog-to-digital conversion","Real-time operating systems (RTOS)","Sensor interfaces","Power management","IoT protocols: MQTT, CoAP","Embedded system testing"],
   "outcomes":["Program ARM microcontrollers in C","Interface with sensors and actuators","Implement interrupt-driven I/O","Use serial communication protocols","Design real-time embedded applications","Build IoT prototypes with sensor networks"]},

  {"course":"CS318","title":"Blockchain and Distributed Ledger Technology","credits":3,"prerequisites":"CS201","corequisites":"None","terms":["Spring"],
   "description":"Study of blockchain technology covering cryptographic foundations, consensus mechanisms, smart contracts, and decentralized applications. Topics include hash functions, digital signatures, Bitcoin protocol, Ethereum and smart contracts (Solidity), consensus algorithms (PoW, PoS, PBFT), decentralized finance (DeFi), and blockchain scalability solutions. CS201 prerequisite provides data structures knowledge (hash tables, trees) essential for understanding blockchain data structures (Merkle trees, hash chains).",
   "topics":["Cryptographic hash functions","Digital signatures and PKI","Bitcoin: UTXO model, mining","Ethereum: accounts model, gas","Smart contracts with Solidity","Consensus: Proof of Work, Proof of Stake, PBFT","Merkle trees and blockchain data structures","Decentralized applications (DApps)","DeFi protocols","Token standards (ERC-20, ERC-721)","Blockchain scalability: Layer 2, sharding","Privacy on blockchain: zero-knowledge proofs"],
   "outcomes":["Explain blockchain consensus mechanisms","Write and deploy smart contracts in Solidity","Analyze blockchain security and attack vectors","Design decentralized applications","Evaluate blockchain scalability solutions","Understand crypto-economic incentive mechanisms"]},

  {"course":"CS319","title":"Introduction to Quantum Computing","credits":3,"prerequisites":"CS202 AND MATH220","corequisites":"None","terms":["Spring"],
   "description":"Introduction to quantum computing covering qubits, quantum gates, quantum circuits, and quantum algorithms. Students study the mathematical foundations of quantum mechanics relevant to computation, including linear algebra over complex vector spaces, tensor products, and measurement. Key algorithms covered include Deutsch-Jozsa, Grover's search, Shor's factoring algorithm, and quantum error correction. Both CS202 (for formal mathematical reasoning) and MATH220 (linear algebra for quantum state representations) are prerequisites.",
   "topics":["Qubits and quantum states","Quantum gates and circuits","Quantum measurement","Quantum entanglement","Deutsch-Jozsa algorithm","Grover's search algorithm","Quantum Fourier transform","Shor's factoring algorithm","Quantum error correction","Quantum key distribution","Quantum machine learning overview","Quantum computing platforms (Qiskit)"],
   "outcomes":["Represent quantum states using Dirac notation","Design quantum circuits using standard gates","Implement quantum algorithms using Qiskit","Analyze quantum algorithm complexity","Understand quantum error correction principles","Compare quantum and classical computational models"]},

  {"course":"CS320","title":"Advanced AI Systems","credits":3,"prerequisites":"CS306","corequisites":"None","terms":["Fall"],
   "description":"Advanced topics in artificial intelligence covering multi-agent systems, automated planning, knowledge graphs, ethical AI, and large language models. Students study multi-agent coordination, STRIPS-style planning, ontologies and semantic web, fairness and bias in AI systems, and the architecture of modern foundation models. Projects involve building complex AI systems that integrate multiple techniques. CS306 (AI) is the prerequisite for foundational AI knowledge including search, reasoning, and probabilistic methods.",
   "topics":["Multi-agent systems and coordination","Automated planning: STRIPS, PDDL","Knowledge graphs and ontologies","Semantic web technologies","Ethical AI and fairness","Bias detection and mitigation","Large language models architecture","Prompt engineering and retrieval-augmented generation","AI safety and alignment","Explainable AI (XAI)","AI governance and regulation","Capstone AI project"],
   "outcomes":["Design multi-agent systems with coordination protocols","Implement automated planning systems","Build and query knowledge graphs","Evaluate AI systems for fairness and bias","Apply prompt engineering techniques with LLMs","Analyze AI safety and ethical implications"]},

  {"course":"CS321","title":"Reinforcement Learning","credits":3,"prerequisites":"CS305","corequisites":"None","terms":["Spring"],
   "description":"Study of reinforcement learning theory and algorithms covering tabular methods, function approximation, policy gradient methods, and deep reinforcement learning. Topics include Markov Decision Processes, value iteration, policy iteration, Monte Carlo methods, temporal difference learning (Q-learning, SARSA), deep Q-networks (DQN), policy gradient (REINFORCE, PPO), and actor-critic methods. Students implement RL agents for games and control tasks. CS305 (Machine Learning) is the prerequisite providing foundations in neural networks, optimization, and model evaluation needed for deep RL methods.",
   "topics":["Markov Decision Processes (MDPs)","Value iteration and policy iteration","Monte Carlo methods","Temporal difference learning","Q-learning and SARSA","Function approximation","Deep Q-Networks (DQN)","Policy gradient methods: REINFORCE","Actor-critic methods: A2C, PPO","Model-based reinforcement learning","Multi-agent reinforcement learning","Applications: games, robotics, control"],
   "outcomes":["Formulate sequential decision problems as MDPs","Implement tabular RL algorithms (Q-learning, SARSA)","Train deep reinforcement learning agents","Apply policy gradient methods","Compare model-free and model-based RL approaches","Design RL solutions for real-world problems"]},

  {"course":"CS322","title":"Deep Learning","credits":3,"prerequisites":"CS305 AND MATH220","corequisites":"None","terms":["Fall"],
   "description":"In-depth study of deep learning covering neural network architectures, training techniques, and applications. Topics include feedforward networks, convolutional neural networks (CNNs), recurrent neural networks (RNNs), generative adversarial networks (GANs), autoencoders, transfer learning, and attention mechanisms. Students implement deep learning models using PyTorch and apply them to computer vision, natural language processing, and generative modeling tasks. Both CS305 (ML foundations) and MATH220 (linear algebra for tensor operations and backpropagation) are required prerequisites.",
   "topics":["Feedforward neural networks and backpropagation","Optimization: SGD, Adam, learning rate schedules","Regularization: dropout, batch normalization","Convolutional Neural Networks (CNNs)","Image classification and object detection","Recurrent Neural Networks and LSTMs","Sequence-to-sequence models","Attention mechanisms and Transformers","Generative Adversarial Networks (GANs)","Autoencoders and variational autoencoders","Transfer learning and fine-tuning","Deep learning with PyTorch"],
   "outcomes":["Design and train deep neural network architectures","Implement CNNs for computer vision tasks","Build sequence models for NLP applications","Apply transfer learning to new domains","Implement generative models (GANs, VAEs)","Use PyTorch for deep learning research and development"]}
]

PROGRAMS = [
  {"program":"Bachelor of Science in Computer Science",
   "type":"major",
   "description":"The Bachelor of Science in Computer Science program prepares students for careers in software development, data science, artificial intelligence, and related computing fields. The program provides a strong foundation in theoretical computer science, practical programming skills, and mathematical reasoning. Students develop expertise through a structured curriculum of core courses, advanced electives, and mathematical foundations. The program requires completion of 120 credit hours including core CS courses, advanced CS electives, mathematics requirements, general education requirements, and free electives. Students must maintain a minimum cumulative GPA of 2.0 and a minimum GPA of 2.5 in CS courses to remain in good standing. A minimum of 60 credit hours must be completed in residence at the university (residency requirement). Students must complete all degree requirements within 6 years of matriculation.",
   "core_courses":["CS101","CS102","CS201","CS202","CS301"],
   "advanced_courses":["CS302","CS303","CS304","CS305","CS306"],
   "math_requirements":["MATH120","MATH220","MATH230"],
   "elective_options":["CS307","CS308","CS309","CS310","CS311","CS312","CS313","CS314","CS315","CS316","CS317","CS318","CS319","CS320","CS321","CS322"],
   "electives_required":3,
   "credits_required":120,
   "cs_credits_minimum":45,
   "residency_credits":60,
   "minimum_gpa":2.0,
   "minimum_cs_gpa":2.5,
   "max_credits_per_semester":18,
   "notes":["Students must complete at least 3 elective courses from the CS elective options list.","A capstone course or senior project is recommended but not required.","Students may petition to substitute one elective with an approved graduate-level course.","Transfer students must complete at least 50% of CS coursework at the university."]},

  {"program":"Artificial Intelligence Specialization Certificate",
   "type":"specialization",
   "description":"The AI Specialization Certificate is available to students enrolled in the BSc Computer Science program who wish to demonstrate focused expertise in artificial intelligence and machine learning. The certificate requires completion of three required courses and two elective courses from the approved list. Students must earn a minimum grade of B in each certificate course. The certificate is noted on the student's transcript upon completion of all requirements and the BSc degree. Students should plan their course sequence carefully as several AI courses have multi-hop prerequisite chains.",
   "requirements":["CS301","CS305","CS306"],
   "electives":["CS307","CS308","CS313","CS314","CS320","CS321","CS322"],
   "electives_required":2,
   "minimum_grade":"B",
   "notes":["All three required courses must be completed with a grade of B or higher.","Students must be enrolled in the BSc Computer Science program.","Certificate is awarded upon completion of BSc degree.","Recommended course sequence: CS301 → CS305/CS306 → electives."]},

  {"program":"Computer Science Minor",
   "type":"minor",
   "description":"The Computer Science Minor is designed for students in other majors who wish to gain foundational knowledge in computer science. The minor requires completion of three required courses and two elective courses from the approved list. Students must earn a minimum grade of C in each minor course. The minor provides sufficient background for students to apply programming and computational thinking in their primary field of study. All minor courses must be completed with the standard grading option (not pass/fail).",
   "requirements":["CS101","CS102","CS201"],
   "electives":["CS202","CS301","CS302","CS304","CS307","CS308","CS311"],
   "electives_required":2,
   "minimum_grade":"C",
   "notes":["All courses must be taken with standard grading (not pass/fail).","At least 3 of the 5 courses must be completed at the university (not transferred).","Students must declare the minor before completing their final semester.","Minor courses may overlap with general education requirements where applicable."]}
]

POLICIES = [
  {"type":"prerequisite_policy","title":"Prerequisite Enforcement Policy",
   "content":"All course prerequisites are strictly enforced at the time of registration. Students must have completed prerequisite courses with a minimum grade of C (2.0) unless a higher grade is specified in the individual course description. Prerequisites marked as 'concurrent' or 'co-requisite' may be taken in the same semester as the course requiring them but may not be taken after. Students who have not met prerequisite requirements will be administratively dropped from the course. In exceptional circumstances, students may petition the department chair for a prerequisite waiver by submitting a Prerequisite Override Request Form along with supporting documentation demonstrating equivalent preparation. Prerequisite waivers are granted at the sole discretion of the department and are not guaranteed. Transfer equivalencies for prerequisite courses must be approved by the Registrar's Office prior to enrollment. Students are responsible for ensuring they have met all prerequisites before registering for courses."},

  {"type":"grading_policy","title":"Grading Scale and Academic Standards",
   "content":"The university uses the following grading scale: A (4.0), A- (3.7), B+ (3.3), B (3.0), B- (2.7), C+ (2.3), C (2.0), C- (1.7), D+ (1.3), D (1.0), F (0.0). A minimum grade of C (2.0) is required for a course to satisfy prerequisite requirements unless otherwise specified. Courses completed with a grade below C do not satisfy prerequisites and must be retaken. The Computer Science department requires a minimum GPA of 2.5 in CS courses for students to remain in good standing in the major. Students whose CS GPA falls below 2.5 for two consecutive semesters will be placed on departmental probation and must meet with their academic advisor to create an improvement plan."},

  {"type":"course_repeat_policy","title":"Course Repeat Policy",
   "content":"Students may repeat a course a maximum of two times (three total attempts). When a course is repeated, the highest grade earned will be used in GPA calculation, but all attempts remain on the transcript. After two unsuccessful attempts (grade below C), students must obtain permission from the department chair before registering for a third attempt. Students on their third attempt may be required to complete additional support such as tutoring or supplemental instruction. Repeated courses count toward attempted credit hours for financial aid satisfactory academic progress calculations."},

  {"type":"credit_load_policy","title":"Credit Load and Registration Policy",
   "content":"The standard credit load is 15 credits per semester. Students may register for a maximum of 18 credits per semester without special permission. Students wishing to exceed 18 credits must petition the Academic Standards Committee and must have a minimum cumulative GPA of 3.5. The minimum credit load for full-time status is 12 credits per semester. Students registered for fewer than 12 credits are considered part-time. Summer session credit limits are 7 credits per summer session and 12 credits for the entire summer. Co-requisite courses must be registered for simultaneously; students may not drop a co-requisite course without also dropping the course that requires it."},

  {"type":"transfer_credit_policy","title":"Transfer Credit and Course Equivalency Policy",
   "content":"Transfer credits from accredited institutions are evaluated by the Registrar's Office on a course-by-course basis. To receive transfer credit for a CS course, the transfer course must cover at least 75% of the topics in the equivalent university course and must have been completed with a grade of C or higher. Transfer credits are recorded as 'TR' on the transcript and are not included in GPA calculations. A maximum of 60 credits may be transferred toward the 120-credit degree requirement. For the BSc Computer Science program, at least 50% of CS course credits must be completed at the university. Students must submit official transcripts and course syllabi for transfer evaluation at least 30 days before the start of the semester."},

  {"type":"academic_integrity_policy","title":"Academic Integrity Policy for CS Courses",
   "content":"The Computer Science department takes academic integrity seriously. All submitted work must be the student's own unless explicitly designated as a group assignment. Collaboration on individual assignments is limited to discussion of concepts; sharing of code, pseudocode, or detailed solutions is prohibited. Use of AI coding assistants (e.g., GitHub Copilot, ChatGPT) is permitted only when explicitly allowed by the instructor in the course syllabus. First violations result in a zero on the assignment and a formal warning. Second violations result in a failing grade for the course. All violations are reported to the Office of Academic Integrity."}
]

SOURCES = [
  {"url":"https://catalog.university.edu/cs/courses/","date_accessed":"2026-03-15","description":"Computer Science course catalog pages containing all CS course descriptions, prerequisites, credit hours, and learning outcomes"},
  {"url":"https://catalog.university.edu/math/courses/","date_accessed":"2026-03-15","description":"Mathematics department course pages for MATH120, MATH220, and MATH230 required by the CS program"},
  {"url":"https://catalog.university.edu/cs/bsc-requirements/","date_accessed":"2026-03-15","description":"BSc Computer Science degree requirements including core courses, electives, math requirements, credit totals, and GPA policies"},
  {"url":"https://catalog.university.edu/cs/ai-specialization/","date_accessed":"2026-03-15","description":"AI Specialization Certificate requirements, eligible courses, and minimum grade requirements"},
  {"url":"https://catalog.university.edu/cs/minor/","date_accessed":"2026-03-15","description":"Computer Science Minor requirements for non-CS majors"},
  {"url":"https://catalog.university.edu/policies/prerequisites/","date_accessed":"2026-03-16","description":"University prerequisite enforcement policy including waiver process and transfer equivalency rules"},
  {"url":"https://catalog.university.edu/policies/grading/","date_accessed":"2026-03-16","description":"Grading scale, minimum grade requirements, and academic standing policies"},
  {"url":"https://catalog.university.edu/policies/course-repeat/","date_accessed":"2026-03-16","description":"Course repeat policy including maximum attempts and GPA calculation rules"},
  {"url":"https://catalog.university.edu/policies/credit-load/","date_accessed":"2026-03-16","description":"Credit load limits, full-time status requirements, and co-requisite registration rules"},
  {"url":"https://catalog.university.edu/policies/transfer/","date_accessed":"2026-03-16","description":"Transfer credit evaluation process and limits for CS degree"},
  {"url":"https://catalog.university.edu/policies/academic-integrity/","date_accessed":"2026-03-16","description":"Academic integrity policy specific to CS courses including AI tool usage policy"}
]

def write_courses():
    d = os.path.join(DATA_DIR, "Courses")
    os.makedirs(d, exist_ok=True)
    # clear old files
    for f in os.listdir(d):
        os.remove(os.path.join(d, f))
    for c in COURSES:
        path = os.path.join(d, f"{c['course'].lower()}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(c, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(COURSES)} course files")

def write_programs():
    d = os.path.join(DATA_DIR, "Programs")
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "programs.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(PROGRAMS, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(PROGRAMS)} programs")

def write_policies():
    d = os.path.join(DATA_DIR, "Policies")
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "policies.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(POLICIES, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(POLICIES)} policies")

def write_sources():
    path = os.path.join(DATA_DIR, "sources.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(SOURCES, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(SOURCES)} sources")

def count_words():
    total = 0
    for r, _, files in os.walk(DATA_DIR):
        for fn in files:
            if fn.endswith(".json"):
                with open(os.path.join(r, fn), encoding="utf-8") as f:
                    total += len(f.read().split())
    print(f"Total word count: {total}")

if __name__ == "__main__":
    write_courses()
    write_programs()
    write_policies()
    write_sources()
    count_words()
    print("Done! All data generated.")
